#pragma once

#include <cstdint>

// === ISS-AUTHORED:BEGIN — generated by the ISS canvas. Edit via the canvas, not by hand. ===
using word = uint32_t;

struct ArchState {
    word x[32] = {};  // General registers
    word pc = 0x80000000;  // Program counter
};

inline ArchState arch;
// === ISS-AUTHORED:END ===
