#pragma once

#include <cstdint>
#include <string>

#include "infra/event.h"

// === ISS-AUTHORED:BEGIN — generated by the ISS canvas. Edit via the canvas, not by hand. ===
class BranchEvent : public Event {
  public:
    BranchEvent() : Event("BranchEvent") { bits = 33; }  // 33 bits on the wire
    bool taken = false;
    uint32_t target = 0;
};

class DecodeEvent : public Event {
  public:
    DecodeEvent() : Event("DecodeEvent") { bits = 64; }  // 64 bits on the wire
    uint32_t opcode = 0;
    uint32_t rd = 0;
};

class ExecEvent : public Event {
  public:
    ExecEvent() : Event("ExecEvent") { bits = 32; }  // 32 bits on the wire
    uint32_t value = 0;
};

class FetchEvent : public Event {
  public:
    FetchEvent() : Event("FetchEvent") { bits = 64; }  // 64 bits on the wire
    uint32_t pc = 0;
    uint32_t instruction = 0;
};

class MemEvent : public Event {
  public:
    MemEvent() : Event("MemEvent") { bits = 32; }  // 32 bits on the wire
    uint32_t value = 0;
};

class MemRequest : public Event {
  public:
    MemRequest() : Event("MemRequest") { bits = 64; }  // 64 bits on the wire
    uint32_t addr = 0;
    uint32_t value = 0;
};

class MEMToOut1Event : public Event {
  public:
    MEMToOut1Event() : Event("MEMToOut1Event") { bits = 32; }  // 32 bits on the wire
};

class Out1ToMemory1Event : public Event {
  public:
    Out1ToMemory1Event() : Event("Out1ToMemory1Event") { bits = 32; }  // 32 bits on the wire
};

class Stage1ToStage2Event : public Event {
  public:
    Stage1ToStage2Event() : Event("Stage1ToStage2Event") { bits = 32; }  // 32 bits on the wire
};

class Stage1ToStage3Event : public Event {
  public:
    Stage1ToStage3Event() : Event("Stage1ToStage3Event") { bits = 32; }  // 32 bits on the wire
};

class Stage2ToStage3Event : public Event {
  public:
    Stage2ToStage3Event() : Event("Stage2ToStage3Event") { bits = 32; }  // 32 bits on the wire
};

class StallEvent : public Event {
  public:
    StallEvent() : Event("StallEvent") { bits = 32; }  // 32 bits on the wire
};
// === ISS-AUTHORED:END ===
