#include <cstdlib>
#include <fstream>
#include <iostream>
#include <memory>

#include "microarch/engine.hpp"
#include "CPU0/Control.cpp"
#include "CPU0/DE.cpp"
#include "CPU0/EX.cpp"
#include "CPU0/IF.cpp"
#include "CPU0/MEM.cpp"
#include "CPU0/Out1.cpp"
#include "CPU0/WB.cpp"
#include "Memory1.cpp"
#include "Unit1/Out1.cpp"
#include "R1.cpp"  // fabric router (latency models live here)
#include "iss_events.h"

// === ISS-AUTHORED:BEGIN — generated by the ISS canvas. Edit via the canvas, not by hand. ===
int main(int argc, char** argv) {
    const uint64_t maxCycles = argc > 1 ? std::strtoull(argv[1], nullptr, 10) : 64;
    std::ofstream traceFile("iss_trace.jsonl");
    microarch::Scheduler scheduler;
    microarch::JsonlTraceWriter trace(traceFile);
    scheduler.setHopSink(trace.hopSink());
    scheduler.setDivergenceSink(trace.divergenceSink());
    scheduler.setMetricSink(trace.metricSink());

    // Fabric routers — instances of their generated src/<R>.cpp classes
    // (clocked: each tick forwards what the port's bit budget pays for).
    R1 r_R1(scheduler);
    scheduler.addClocked(r_R1);

    // One link per authored out-port.
    microarch::Link link_CPU0_Control_stall(scheduler, 1);
    microarch::Link link_CPU0_DE_out(scheduler, 1);
    microarch::Link link_CPU0_EX_out(scheduler, 1);
    microarch::Link link_CPU0_EX_branch(scheduler, 0);
    microarch::Link link_CPU0_IF_out(scheduler, 1);
    microarch::Link link_CPU0_MEM_out(scheduler, 1);
    microarch::Link link_CPU0_MEM_out_MEM_to_Out1(scheduler, 100);
    microarch::Link link_CPU0_Out1_out_Out1_to_Memory1(scheduler, 1);

    // Blocks receive their out-links positionally (writer ctor order).
    // sv-impl blocks instantiate their co-sim adapter, not the C++ class.
    CPU0::Control s_CPU0_Control(&link_CPU0_Control_stall);
    CPU0::DE s_CPU0_DE(&link_CPU0_DE_out);
    CPU0::EX s_CPU0_EX(&link_CPU0_EX_out, &link_CPU0_EX_branch);
    CPU0::IF s_CPU0_IF(&link_CPU0_IF_out);
    CPU0::MEM s_CPU0_MEM(&link_CPU0_MEM_out, &link_CPU0_MEM_out_MEM_to_Out1);
    CPU0::Out1 s_CPU0_Out1(&link_CPU0_Out1_out_Out1_to_Memory1);
    CPU0::WB s_CPU0_WB;
    Memory1 s_Memory1;
    Unit1::Out1 s_Unit1_Out1;

    // Registry + per-block wire(): every drawn connection, in code.
    microarch::Registry registry;
    registry.add("CPU0.Control", s_CPU0_Control);
    registry.add("CPU0.DE", s_CPU0_DE);
    registry.add("CPU0.EX", s_CPU0_EX);
    registry.add("CPU0.IF", s_CPU0_IF);
    registry.add("CPU0.MEM", s_CPU0_MEM);
    registry.add("CPU0.Out1", s_CPU0_Out1);
    registry.add("CPU0.WB", s_CPU0_WB);
    registry.add("Memory1", s_Memory1);
    registry.add("Unit1.Out1", s_Unit1_Out1);
    s_CPU0_Control.wire(registry);
    s_CPU0_DE.wire(registry);
    s_CPU0_EX.wire(registry);
    s_CPU0_IF.wire(registry);
    s_CPU0_MEM.wire(registry);
    s_CPU0_Out1.wire(registry);
    s_CPU0_WB.wire(registry);
    s_Memory1.wire(registry);
    s_Unit1_Out1.wire(registry);

    // Fabric transport: inter-composite dataflow is authored as ordered
    // forwarding rules on the routers. A fabric-bound port enters its top's
    // attachment router destination-less; the ingress router matches
    // (message type, address) in rule order, stamps the destination, and
    // the dest-keyed hop tables carry it. Unmatched packets drop + report.
    r_R1.addMatchRule("Out1ToMemory1Event", 0x0ULL, 0xffffffffffffffffULL, "Memory1");  // rule 1: Out1ToMemory1Event -> Memory1
    r_R1.addRoute("Memory1", s_Memory1);
    link_CPU0_Out1_out_Out1_to_Memory1.routeVia(r_R1);  // fabric ingress: CPU0.Out1.out_Out1_to_Memory1 (Out1ToMemory1Event) -> R1

    // Seed 8 tokens, one per cycle, into the entry block(s) (auto-detected).
    for (uint64_t c = 0; c < 8; ++c)
        scheduler.seed(std::make_unique<microarch::Event>("Event"), s_Unit1_Out1, c);

    scheduler.runFor(maxCycles);
    if (r_R1.pendingCount() > 0)
        std::cout << "router R1: " << r_R1.pendingCount() << " event(s) still queued at clock stop\n";
    std::cout << "ran " << scheduler.currentCycle() << " cycles; trace: iss_trace.jsonl\n";
    return 0;
}
// === ISS-AUTHORED:END ===
