#pragma once

#include <cstring>
#include <memory>

#include "infra/component.h"
#include "infra/event.h"
#include "infra/link.h"
#include "iss_events.h"
#include "microarch/registry.hpp"

// === ISS-AUTHORED:BEGIN — generated by the ISS canvas. Edit via the canvas, not by hand. ===
class Memory1 : public Component {
  private:
    uint64_t accesses = 0;
  public:
    explicit Memory1() : Component("Memory1") {
        configureLink();
    }
    void handler(Event& ev) override {
        if (ev.type() == "MemRequest") {
            auto& msg_MemRequest = static_cast<MemRequest&>(ev);
            (void)msg_MemRequest;
        }
        if (ev.type() == "Out1ToMemory1Event") {
            auto& msg_Out1ToMemory1Event = static_cast<Out1ToMemory1Event&>(ev);
            (void)msg_Out1ToMemory1Event;
        }
    }
    void setLink(const char* port, Link* link) {
        (void)port;
        (void)link;
    }
    void configureLink() {
    }
    void wire(microarch::Registry& registry) {
        (void)registry;
    }
};
// === ISS-AUTHORED:END ===
