#pragma once

#include "microarch/engine.hpp"
#include "iss_events.h"

// === ISS-AUTHORED:BEGIN — generated by the ISS canvas. Edit via the canvas, not by hand. ===
class R1 : public microarch::Router {
  public:
    explicit R1(microarch::Scheduler& scheduler)
        : microarch::Router("R1", scheduler, 1) {}

    // The default: every route without an assigned model forwards in a
    // flat constant number of cycles (the latency in the inspector).
    microarch::Cycle flat(const microarch::Event&) const { return 1; }
// === ISS-AUTHORED:END ===

    // Hand-written latency models live here and survive regeneration.
    // Each model is a member function returning cycles for one packet:
    //
    //     microarch::Cycle congested(const microarch::Event& event) {
    //         return event.token % 4 == 0 ? 6 : 2;
    //     }
    //
    // Assign a model to a routed wire in the inspector (wire panel of a
    // connection riding R1); unassigned wires use flat().

};
