#pragma once

#include <cstring>
#include <memory>

#include "infra/component.h"
#include "infra/event.h"
#include "infra/link.h"
#include "iss_events.h"
#include "microarch/registry.hpp"

// === ISS-AUTHORED:BEGIN — generated by the ISS canvas. Edit via the canvas, not by hand. ===
namespace CPU0 {

class Control : public Component {
  private:
    Link* stall;
  public:
    explicit Control(Link* stall = nullptr) : Component("CPU0.Control"), stall(stall) {
        configureLink();
    }
    void handler(Event& ev) override {
        if (ev.type() == "BranchEvent") {
            auto& msg_BranchEvent = static_cast<BranchEvent&>(ev);
            (void)msg_BranchEvent;
        }
        if (stall && stall->connected()) {
            auto ev_stall = std::make_unique<StallEvent>();
            stall->send(std::move(ev_stall));
        }
    }
    void setLink(const char* port, Link* link) {
        if (std::strcmp(port, "stall") == 0) this->stall = link;
        configureLink();
    }
    void configureLink() {
        if (stall) {
            stall->configureIn(this);
            stall->latency = 1;
        }
    }
    void wire(microarch::Registry& registry) {
        if (stall) stall->configureOut(registry.find("CPU0.IF"));  // wire: CPU0.Control.stall -> CPU0.IF (StallEvent)
    }
};

} // namespace CPU0
// === ISS-AUTHORED:END ===
