#pragma once

#include <cstring>
#include <memory>

#include "infra/component.h"
#include "infra/event.h"
#include "infra/link.h"
#include "iss_events.h"
#include "microarch/registry.hpp"

// === ISS-AUTHORED:BEGIN — generated by the ISS canvas. Edit via the canvas, not by hand. ===
namespace CPU0 {

class DE : public Component {
  private:
    Link* out;
    uint32_t instruction = 0;
    uint32_t opcode = 0;
  public:
    explicit DE(Link* out = nullptr) : Component("CPU0.DE"), out(out) {
        configureLink();
    }
    void handler(Event& ev) override {
        if (ev.type() == "FetchEvent") {
            auto& msg_FetchEvent = static_cast<FetchEvent&>(ev);
            (void)msg_FetchEvent;
        }
        if (out && out->connected()) {
            auto ev_out = std::make_unique<DecodeEvent>();
            out->send(std::move(ev_out));
        }
    }
    void setLink(const char* port, Link* link) {
        if (std::strcmp(port, "out") == 0) this->out = link;
        configureLink();
    }
    void configureLink() {
        if (out) {
            out->configureIn(this);
            out->latency = 1;
        }
    }
    void wire(microarch::Registry& registry) {
        if (out) out->configureOut(registry.find("CPU0.EX"));  // wire: CPU0.DE.out -> CPU0.EX (DecodeEvent)
    }
};

} // namespace CPU0
// === ISS-AUTHORED:END ===
