// SystemVerilog twin — the co-simulation contract for this block.
// Ports mirror the block’s event interface; write the behavior below the
// generated region (hand edits there survive regeneration).
// === ISS-AUTHORED:BEGIN — generated by the ISS canvas. Edit via the canvas, not by hand. ===
module DE (
    /* verilator lint_off UNUSEDSIGNAL */
    input  logic clk,
    input  logic rst,
    // in: FetchEvent
    input  logic FetchEvent_valid,
    input  logic [31:0] FetchEvent_pc,
    input  logic [31:0] FetchEvent_instruction,
    // out out: DecodeEvent → CPU0.EX
    output logic out_valid,
    output logic [31:0] out_opcode,
    output logic [31:0] out_rd
    /* verilator lint_on UNUSEDSIGNAL */
);
// === ISS-AUTHORED:END ===

    // TODO: behavioral twin of the C++ block. Replace the placeholder
    // drives with real behavior; this body survives regeneration.
    always_ff @(posedge clk) begin
        if (rst) begin
            out_valid <= 1'b0;
            out_opcode <= '0;
            out_rd <= '0;
        end
    end

endmodule
