#pragma once

#include <cstring>
#include <memory>

#include "infra/component.h"
#include "infra/event.h"
#include "infra/link.h"
#include "iss_events.h"
#include "microarch/registry.hpp"

// === ISS-AUTHORED:BEGIN — generated by the ISS canvas. Edit via the canvas, not by hand. ===
namespace CPU0 {

class EX : public Component {
  private:
    Link* out;
    Link* branch;
    uint32_t result = 0;
  public:
    explicit EX(Link* out = nullptr, Link* branch = nullptr) : Component("CPU0.EX"), out(out), branch(branch) {
        configureLink();
    }
    void handler(Event& ev) override {
        if (ev.type() == "DecodeEvent") {
            auto& msg_DecodeEvent = static_cast<DecodeEvent&>(ev);
            (void)msg_DecodeEvent;
        }
        if (out && out->connected()) {
            auto ev_out = std::make_unique<ExecEvent>();
            out->send(std::move(ev_out));
        }
        if (branch && branch->connected()) {
            auto ev_branch = std::make_unique<BranchEvent>();
            branch->send(std::move(ev_branch));
        }
    }
    void setLink(const char* port, Link* link) {
        if (std::strcmp(port, "out") == 0) this->out = link;
        if (std::strcmp(port, "branch") == 0) this->branch = link;
        configureLink();
    }
    void configureLink() {
        if (out) {
            out->configureIn(this);
            out->latency = 1;
        }
        if (branch) {
            branch->configureIn(this);
            branch->latency = 0;
        }
    }
    void wire(microarch::Registry& registry) {
        if (out) out->configureOut(registry.find("CPU0.MEM"));  // wire: CPU0.EX.out -> CPU0.MEM (ExecEvent)
        if (branch) branch->configureOut(registry.find("CPU0.Control"));  // wire: CPU0.EX.branch -> CPU0.Control (BranchEvent)
    }
};

} // namespace CPU0
// === ISS-AUTHORED:END ===
