// SystemVerilog twin — the co-simulation contract for this block.
// Ports mirror the block’s event interface; write the behavior below the
// generated region (hand edits there survive regeneration).
// === ISS-AUTHORED:BEGIN — generated by the ISS canvas. Edit via the canvas, not by hand. ===
module EX (
    /* verilator lint_off UNUSEDSIGNAL */
    input  logic clk,
    input  logic rst,
    // in: DecodeEvent
    input  logic DecodeEvent_valid,
    input  logic [31:0] DecodeEvent_opcode,
    input  logic [31:0] DecodeEvent_rd,
    // out out: ExecEvent → CPU0.MEM
    output logic out_valid,
    output logic [31:0] out_value,
    // out branch: BranchEvent → CPU0.Control
    output logic branch_valid,
    output logic branch_taken,
    output logic [31:0] branch_target
    /* verilator lint_on UNUSEDSIGNAL */
);
// === ISS-AUTHORED:END ===

    // TODO: behavioral twin of the C++ block. Replace the placeholder
    // drives with real behavior; this body survives regeneration.
    always_ff @(posedge clk) begin
        if (rst) begin
            out_valid <= 1'b0;
            out_value <= '0;
            branch_valid <= 1'b0;
            branch_taken <= '0;
            branch_target <= '0;
        end
    end

endmodule
