#pragma once

#include <cstring>
#include <memory>

#include "infra/component.h"
#include "infra/event.h"
#include "infra/link.h"
#include "iss_events.h"
#include "microarch/registry.hpp"

// === ISS-AUTHORED:BEGIN — generated by the ISS canvas. Edit via the canvas, not by hand. ===
namespace CPU0 {

class IF : public Component {
  private:
    Link* out;
    uint32_t pc = 0x80000000;
  public:
    explicit IF(Link* out = nullptr) : Component("CPU0.IF"), out(out) {
        configureLink();
    }
    void handler(Event& ev) override {
        if (ev.type() == "StallEvent") {
            auto& msg_StallEvent = static_cast<StallEvent&>(ev);
            (void)msg_StallEvent;
        }
        if (out && out->connected()) {
            auto ev_out = std::make_unique<FetchEvent>();
            out->send(std::move(ev_out));
        }
    }
    void setLink(const char* port, Link* link) {
        if (std::strcmp(port, "out") == 0) this->out = link;
        configureLink();
    }
    void configureLink() {
        if (out) {
            out->configureIn(this);
            out->latency = 1;
        }
    }
    void wire(microarch::Registry& registry) {
        if (out) out->configureOut(registry.find("CPU0.DE"));  // wire: CPU0.IF.out -> CPU0.DE (FetchEvent)
    }
};

} // namespace CPU0
// === ISS-AUTHORED:END ===
