#pragma once

#include <cstring>
#include <memory>

#include "infra/component.h"
#include "infra/event.h"
#include "infra/link.h"
#include "iss_events.h"
#include "microarch/registry.hpp"

// === ISS-AUTHORED:BEGIN — generated by the ISS canvas. Edit via the canvas, not by hand. ===
namespace CPU0 {

class MEM : public Component {
  private:
    Link* out;
    Link* out_MEM_to_Out1;
  public:
    explicit MEM(Link* out = nullptr, Link* out_MEM_to_Out1 = nullptr) : Component("CPU0.MEM"), out(out), out_MEM_to_Out1(out_MEM_to_Out1) {
        configureLink();
    }
    void handler(Event& ev) override {
        if (ev.type() == "ExecEvent") {
            auto& msg_ExecEvent = static_cast<ExecEvent&>(ev);
            (void)msg_ExecEvent;
        }
        if (out && out->connected()) {
            auto ev_out = std::make_unique<MemEvent>();
            out->send(std::move(ev_out));
        }
        if (out_MEM_to_Out1 && out_MEM_to_Out1->connected()) {
            auto ev_out_MEM_to_Out1 = std::make_unique<MEMToOut1Event>();
            out_MEM_to_Out1->send(std::move(ev_out_MEM_to_Out1));
        }
    }
    void setLink(const char* port, Link* link) {
        if (std::strcmp(port, "out") == 0) this->out = link;
        if (std::strcmp(port, "out_MEM_to_Out1") == 0) this->out_MEM_to_Out1 = link;
        configureLink();
    }
    void configureLink() {
        if (out) {
            out->configureIn(this);
            out->latency = 1;
        }
        if (out_MEM_to_Out1) {
            out_MEM_to_Out1->configureIn(this);
            out_MEM_to_Out1->latency = 100;
        }
    }
    void wire(microarch::Registry& registry) {
        if (out) out->configureOut(registry.find("CPU0.WB"));  // wire: CPU0.MEM.out -> CPU0.WB (MemEvent)
        if (out_MEM_to_Out1) out_MEM_to_Out1->configureOut(registry.find("CPU0.Out1"));  // wire: CPU0.MEM.out_MEM_to_Out1 -> CPU0.Out1 (MEMToOut1Event)
    }
};

} // namespace CPU0
// === ISS-AUTHORED:END ===
