// SystemVerilog twin — the co-simulation contract for this block.
// Ports mirror the block’s event interface; write the behavior below the
// generated region (hand edits there survive regeneration).
// === ISS-AUTHORED:BEGIN — generated by the ISS canvas. Edit via the canvas, not by hand. ===
module MEM (
    /* verilator lint_off UNUSEDSIGNAL */
    input  logic clk,
    input  logic rst,
    // in: ExecEvent
    input  logic ExecEvent_valid,
    input  logic [31:0] ExecEvent_value,
    // out out: MemEvent → CPU0.WB
    output logic out_valid,
    output logic [31:0] out_value,
    // out out_MEM_to_Out1: MEMToOut1Event → CPU0.Out1
    output logic out_MEM_to_Out1_valid
    /* verilator lint_on UNUSEDSIGNAL */
);
// === ISS-AUTHORED:END ===

    // TODO: behavioral twin of the C++ block. Replace the placeholder
    // drives with real behavior; this body survives regeneration.
    always_ff @(posedge clk) begin
        if (rst) begin
            out_valid <= 1'b0;
            out_value <= '0;
            out_MEM_to_Out1_valid <= 1'b0;
        end
    end

endmodule
