// SystemVerilog twin — the co-simulation contract for this block.
// Ports mirror the block’s event interface; write the behavior below the
// generated region (hand edits there survive regeneration).
// === ISS-AUTHORED:BEGIN — generated by the ISS canvas. Edit via the canvas, not by hand. ===
module Out1 (
    /* verilator lint_off UNUSEDSIGNAL */
    input  logic clk,
    input  logic rst,
    // in: MEMToOut1Event
    input  logic MEMToOut1Event_valid,
    // out out_Out1_to_Memory1: Out1ToMemory1Event
    output logic out_Out1_to_Memory1_valid
    /* verilator lint_on UNUSEDSIGNAL */
);
// === ISS-AUTHORED:END ===

    // TODO: behavioral twin of the C++ block. Replace the placeholder
    // drives with real behavior; this body survives regeneration.
    always_ff @(posedge clk) begin
        if (rst) begin
            out_Out1_to_Memory1_valid <= 1'b0;
        end
    end

endmodule
