#pragma once

#include <cstring>
#include <memory>

#include "infra/component.h"
#include "infra/event.h"
#include "infra/link.h"
#include "iss_events.h"
#include "microarch/registry.hpp"

// === ISS-AUTHORED:BEGIN — generated by the ISS canvas. Edit via the canvas, not by hand. ===
namespace CPU0 {

class Out1 : public Component {
  private:
    Link* out_Out1_to_Memory1;
  public:
    explicit Out1(Link* out_Out1_to_Memory1 = nullptr) : Component("CPU0.Out1"), out_Out1_to_Memory1(out_Out1_to_Memory1) {
        configureLink();
    }
    void handler(Event& ev) override {
        if (ev.type() == "MEMToOut1Event") {
            auto& msg_MEMToOut1Event = static_cast<MEMToOut1Event&>(ev);
            (void)msg_MEMToOut1Event;
        }
        if (out_Out1_to_Memory1 && out_Out1_to_Memory1->connected()) {
            auto ev_out_Out1_to_Memory1 = std::make_unique<Out1ToMemory1Event>();
            out_Out1_to_Memory1->send(std::move(ev_out_Out1_to_Memory1));
        }
    }
    void setLink(const char* port, Link* link) {
        if (std::strcmp(port, "out_Out1_to_Memory1") == 0) this->out_Out1_to_Memory1 = link;
        configureLink();
    }
    void configureLink() {
        if (out_Out1_to_Memory1) {
            out_Out1_to_Memory1->configureIn(this);
            out_Out1_to_Memory1->latency = 1;
        }
    }
    void wire(microarch::Registry& registry) {
        (void)registry;
    }
};

} // namespace CPU0
// === ISS-AUTHORED:END ===
