#pragma once

#include <cstring>
#include <memory>

#include "infra/component.h"
#include "infra/event.h"
#include "infra/link.h"
#include "iss_events.h"
#include "microarch/registry.hpp"

// === ISS-AUTHORED:BEGIN — generated by the ISS canvas. Edit via the canvas, not by hand. ===
namespace CPU0 {

class WB : public Component {
  private:
    uint64_t retired = 0;
  public:
    explicit WB() : Component("CPU0.WB") {
        configureLink();
    }
    void handler(Event& ev) override {
        if (ev.type() == "MemEvent") {
            auto& msg_MemEvent = static_cast<MemEvent&>(ev);
            (void)msg_MemEvent;
        }
    }
    void setLink(const char* port, Link* link) {
        (void)port;
        (void)link;
    }
    void configureLink() {
    }
    void wire(microarch::Registry& registry) {
        (void)registry;
    }
};

} // namespace CPU0
// === ISS-AUTHORED:END ===
