// SystemVerilog twin — the co-simulation contract for this block.
// Ports mirror the block’s event interface; write the behavior below the
// generated region (hand edits there survive regeneration).
// === ISS-AUTHORED:BEGIN — generated by the ISS canvas. Edit via the canvas, not by hand. ===
module WB (
    /* verilator lint_off UNUSEDSIGNAL */
    input  logic clk,
    input  logic rst,
    // in: MemEvent
    input  logic MemEvent_valid,
    input  logic [31:0] MemEvent_value
    /* verilator lint_on UNUSEDSIGNAL */
);
// === ISS-AUTHORED:END ===

    // TODO: behavioral twin of the C++ block. Replace the placeholder
    // drives with real behavior; this body survives regeneration.
    always_ff @(posedge clk) begin
        if (rst) begin
        end
    end

endmodule
