#pragma once

#include <cstring>
#include <memory>

#include "infra/component.h"
#include "infra/event.h"
#include "infra/link.h"
#include "iss_events.h"
#include "microarch/registry.hpp"
#include "microarch/scheduler.hpp"

// === ISS-AUTHORED:BEGIN — generated by the ISS canvas. Edit via the canvas, not by hand. ===
class Gen1 : public Component {
  private:
    uint64_t sent_ = 0;
    uint64_t rr_ = 0;
    uint64_t lfsr_ = 0x2545F4914F6CDD1DULL;
    uint64_t addrSeq_ = 0;
    microarch::Scheduler& scheduler_;
  public:
    explicit Gen1(microarch::Scheduler& scheduler) : Component("Gen1"), scheduler_(scheduler) {
        configureLink();
    }

    void handler(Event& ev) override {
        (void)ev;
    }

    void setLink(const char* port, Link* link) {
        (void)port;
        (void)link;
    }

    void configureLink() {
    }

    void wire(microarch::Registry& registry) {
        (void)registry;
    }

    void tick(microarch::Cycle cycle) override {
        (void)cycle;  // no out-ports yet — draw a wire to generate
    }
};
// === ISS-AUTHORED:END ===
