#include <cstdlib>
#include <fstream>
#include <iostream>
#include <memory>

#include "microarch/engine.hpp"
#include "Gen1.cpp"
#include "Memory1.cpp"
#include "Memory2.cpp"
#include "Memory3.cpp"
#include "Memory4.cpp"
#include "Unit1/Stage1.cpp"
#include "Unit1/Stage2.cpp"
#include "R1.cpp"  // fabric router (latency models live here)
#include "R2.cpp"  // fabric router (latency models live here)
#include "R3.cpp"  // fabric router (latency models live here)
#include "iss_events.h"

// === ISS-AUTHORED:BEGIN — generated by the ISS canvas. Edit via the canvas, not by hand. ===
int main(int argc, char** argv) {
    const uint64_t maxCycles = argc > 1 ? std::strtoull(argv[1], nullptr, 10) : 64;
    std::ofstream traceFile("iss_trace.jsonl");
    microarch::Scheduler scheduler;
    microarch::JsonlTraceWriter trace(traceFile);
    scheduler.setHopSink(trace.hopSink());
    scheduler.setDivergenceSink(trace.divergenceSink());
    scheduler.setMetricSink(trace.metricSink());

    // Fabric routers — instances of their generated src/<R>.cpp classes
    // (clocked: each tick forwards what the port's bit budget pays for).
    R1 r_R1(scheduler);
    scheduler.addClocked(r_R1);
    R2 r_R2(scheduler);
    scheduler.addClocked(r_R2);
    R3 r_R3(scheduler);
    scheduler.addClocked(r_R3);

    // One link per authored out-port.
    microarch::Link link_Unit1_Stage1_out_Stage1_to_Stage2(scheduler, 1);

    // Blocks receive their out-links positionally (writer ctor order).
    // sv-impl blocks instantiate their co-sim adapter, not the C++ class.
    Gen1 s_Gen1(scheduler);
    Memory1 s_Memory1;
    Memory2 s_Memory2;
    Memory3 s_Memory3;
    Memory4 s_Memory4;
    Unit1::Stage1 s_Unit1_Stage1(&link_Unit1_Stage1_out_Stage1_to_Stage2);
    Unit1::Stage2 s_Unit1_Stage2;

    // Registry + per-block wire(): every drawn connection, in code.
    microarch::Registry registry;
    registry.add("Gen1", s_Gen1);
    registry.add("Memory1", s_Memory1);
    registry.add("Memory2", s_Memory2);
    registry.add("Memory3", s_Memory3);
    registry.add("Memory4", s_Memory4);
    registry.add("Unit1.Stage1", s_Unit1_Stage1);
    registry.add("Unit1.Stage2", s_Unit1_Stage2);
    s_Gen1.wire(registry);
    s_Memory1.wire(registry);
    s_Memory2.wire(registry);
    s_Memory3.wire(registry);
    s_Memory4.wire(registry);
    s_Unit1_Stage1.wire(registry);
    s_Unit1_Stage2.wire(registry);

    // Fabric transport: inter-composite dataflow is authored as ordered
    // forwarding rules on the routers. A fabric-bound port enters its top's
    // attachment router destination-less; the ingress router matches
    // (message type, address) in rule order, stamps the destination, and
    // the dest-keyed hop tables carry it. Unmatched packets drop + report.
    r_R1.addMatchRule("Gen1ToMemory1Event", 0x0ULL, 0xfffULL, "Memory1");  // rule 1: Gen1ToMemory1Event [0x0..0xfff] -> Memory1
    r_R1.addMatchRule("Gen1ToMemory1Event", 0x1000ULL, 0x1fffULL, "Memory2");  // rule 2: Gen1ToMemory1Event [0x1000..0x1fff] -> Memory2
    r_R1.addMatchRule("Memory1ToMemory2Event", 0x0ULL, 0xffffffffffffffffULL, "Memory2");  // rule 3: Memory1ToMemory2Event -> Memory2
    r_R1.addMatchRule("Memory1ToMemory3Event", 0x0ULL, 0xffffffffffffffffULL, "Memory3");  // rule 4: Memory1ToMemory3Event -> Memory3
    r_R1.addRoute("Memory1", s_Memory1);
    r_R1.addRoute("Memory2", s_Memory2);
    r_R1.addRoute("Memory3", s_Memory3);

    // Traffic generators are clocked: tick() originates their packets.
    scheduler.addClocked(s_Gen1);

    // Seed 8 tokens, one per cycle, into the entry block(s) (auto-detected).
    for (uint64_t c = 0; c < 8; ++c)
        scheduler.seed(std::make_unique<microarch::Event>("Event"), s_Memory4, c);
    for (uint64_t c = 0; c < 8; ++c)
        scheduler.seed(std::make_unique<microarch::Event>("Event"), s_Unit1_Stage1, c);

    scheduler.runFor(maxCycles);
    if (r_R1.pendingCount() > 0)
        std::cout << "router R1: " << r_R1.pendingCount() << " event(s) still queued at clock stop\n";
    if (r_R2.pendingCount() > 0)
        std::cout << "router R2: " << r_R2.pendingCount() << " event(s) still queued at clock stop\n";
    if (r_R3.pendingCount() > 0)
        std::cout << "router R3: " << r_R3.pendingCount() << " event(s) still queued at clock stop\n";
    std::cout << "ran " << scheduler.currentCycle() << " cycles; trace: iss_trace.jsonl\n";
    return 0;
}
// === ISS-AUTHORED:END ===
