#pragma once

#include <cstring>
#include <memory>

#include "infra/component.h"
#include "infra/event.h"
#include "infra/link.h"
#include "iss_events.h"
#include "microarch/registry.hpp"

// === ISS-AUTHORED:BEGIN — generated by the ISS canvas. Edit via the canvas, not by hand. ===
class Memory3 : public Component {
  public:
    explicit Memory3() : Component("Memory3") {
        configureLink();
    }
    void handler(Event& ev) override {
        if (ev.type() == "Memory1ToMemory3Event") {
            auto& msg_Memory1ToMemory3Event = static_cast<Memory1ToMemory3Event&>(ev);
            (void)msg_Memory1ToMemory3Event;
        }
    }
    void setLink(const char* port, Link* link) {
        (void)port;
        (void)link;
    }
    void configureLink() {
    }
    void wire(microarch::Registry& registry) {
        (void)registry;
    }
};
// === ISS-AUTHORED:END ===
