#pragma once

#include <cstring>
#include <memory>

#include "infra/component.h"
#include "infra/event.h"
#include "infra/link.h"
#include "iss_events.h"
#include "microarch/registry.hpp"

// === ISS-AUTHORED:BEGIN — generated by the ISS canvas. Edit via the canvas, not by hand. ===
class Memory1 : public Component {
  public:
    explicit Memory1() : Component("Memory1") {
        configureLink();
    }
    void handler(Event& ev) override {
        if (ev.type() == "fetchWord") {
            auto& msg_fetchWord = static_cast<fetchWord&>(ev);
            (void)msg_fetchWord;
        }
    }
    void setLink(const char* port, Link* link) {
        (void)port;
        (void)link;
    }
    void configureLink() {
    }
    void wire(microarch::Registry& registry) {
        (void)registry;
    }
};
// === ISS-AUTHORED:END ===
