#pragma once

#include <cstring>
#include <memory>

#include "infra/component.h"
#include "infra/event.h"
#include "infra/link.h"
#include "iss_events.h"
#include "microarch/registry.hpp"

// === ISS-AUTHORED:BEGIN — generated by the ISS canvas. Edit via the canvas, not by hand. ===
class Memory2 : public Component {
  public:
    explicit Memory2() : Component("Memory2") {
        configureLink();
    }
    void handler(Event& ev) override {
        if (ev.type() == "Gen1ToMemory2Event") {
            auto& msg_Gen1ToMemory2Event = static_cast<Gen1ToMemory2Event&>(ev);
            (void)msg_Gen1ToMemory2Event;
        }
        if (ev.type() == "Memory1ToMemory2Event") {
            auto& msg_Memory1ToMemory2Event = static_cast<Memory1ToMemory2Event&>(ev);
            (void)msg_Memory1ToMemory2Event;
        }
        if (ev.type() == "Gen1ToMemory1Event") {
            auto& msg_Gen1ToMemory1Event = static_cast<Gen1ToMemory1Event&>(ev);
            (void)msg_Gen1ToMemory1Event;
        }
    }
    void setLink(const char* port, Link* link) {
        (void)port;
        (void)link;
    }
    void configureLink() {
    }
    void wire(microarch::Registry& registry) {
        (void)registry;
    }
};
// === ISS-AUTHORED:END ===
