#pragma once

#include <cstdint>
#include <string>

#include "infra/event.h"
#include "iss_arch.h"

// === ISS-AUTHORED:BEGIN — generated by the ISS canvas. Edit via the canvas, not by hand. ===
class fetchWord : public Event {
  public:
    fetchWord() : Event("fetchWord") { bits = 32; }  // 32 bits on the wire
};

class Gen1ToMemory1Event : public Event {
  public:
    Gen1ToMemory1Event() : Event("Gen1ToMemory1Event") { bits = 32; }  // 32 bits on the wire
};

class Gen1ToMemory2Event : public Event {
  public:
    Gen1ToMemory2Event() : Event("Gen1ToMemory2Event") { bits = 32; }  // 32 bits on the wire
};

class Memory1ToMemory2Event : public Event {
  public:
    Memory1ToMemory2Event() : Event("Memory1ToMemory2Event") { bits = 32; }  // 32 bits on the wire
};

class Memory1ToMemory3Event : public Event {
  public:
    Memory1ToMemory3Event() : Event("Memory1ToMemory3Event") { bits = 32; }  // 32 bits on the wire
};

class Stage1ToStage2Event : public Event {
  public:
    Stage1ToStage2Event() : Event("Stage1ToStage2Event") { bits = 32; }  // 32 bits on the wire
};
// === ISS-AUTHORED:END ===
