#pragma once

#include <cstring>
#include <memory>

#include "infra/component.h"
#include "infra/event.h"
#include "infra/link.h"
#include "iss_events.h"
#include "microarch/registry.hpp"

// === ISS-AUTHORED:BEGIN — generated by the ISS canvas. Edit via the canvas, not by hand. ===
namespace Unit1 {

class Stage2 : public Component {
  public:
    explicit Stage2() : Component("Unit1.Stage2") {
        configureLink();
    }
    void handler(Event& ev) override {
        if (ev.type() == "Stage1ToStage2Event") {
            auto& msg_Stage1ToStage2Event = static_cast<Stage1ToStage2Event&>(ev);
            (void)msg_Stage1ToStage2Event;
        }
    }
    void setLink(const char* port, Link* link) {
        (void)port;
        (void)link;
    }
    void configureLink() {
    }
    void wire(microarch::Registry& registry) {
        (void)registry;
    }
};

} // namespace Unit1
// === ISS-AUTHORED:END ===
