#pragma once

#include <cstring>
#include <memory>

#include "infra/component.h"
#include "infra/event.h"
#include "infra/link.h"
#include "iss_events.h"
#include "microarch/registry.hpp"

// === ISS-AUTHORED:BEGIN — generated by the ISS canvas. Edit via the canvas, not by hand. ===
namespace Unit1 {

class Stage1 : public Component {
  private:
    Link* out_Stage1_to_Stage2;
  public:
    explicit Stage1(Link* out_Stage1_to_Stage2 = nullptr) : Component("Unit1.Stage1"), out_Stage1_to_Stage2(out_Stage1_to_Stage2) {
        configureLink();
    }
    void handler(Event& ev) override {
        (void)ev;
        if (out_Stage1_to_Stage2 && out_Stage1_to_Stage2->connected()) {
            auto ev_out_Stage1_to_Stage2 = std::make_unique<Stage1ToStage2Event>();
            out_Stage1_to_Stage2->send(std::move(ev_out_Stage1_to_Stage2));
        }
    }
    void setLink(const char* port, Link* link) {
        if (std::strcmp(port, "out_Stage1_to_Stage2") == 0) this->out_Stage1_to_Stage2 = link;
        configureLink();
    }
    void configureLink() {
        if (out_Stage1_to_Stage2) {
            out_Stage1_to_Stage2->configureIn(this);
            out_Stage1_to_Stage2->latency = 1;
        }
    }
    void wire(microarch::Registry& registry) {
        if (out_Stage1_to_Stage2) out_Stage1_to_Stage2->configureOut(registry.find("Unit1.Stage2"));  // wire: Unit1.Stage1.out_Stage1_to_Stage2 -> Unit1.Stage2 (Stage1ToStage2Event)
    }
};

} // namespace Unit1
// === ISS-AUTHORED:END ===
