// Marker-region splice: the canvas only ever rewrites the text BETWEEN the
// markers; everything before BEGIN and after END is byte-preserved, so hand
// edits outside the region survive every regeneration.

export const BEGIN_MARKER =
  '// === ISS-AUTHORED:BEGIN — generated by the ISS canvas. Edit via the canvas, not by hand. ===';
export const END_MARKER = '// === ISS-AUTHORED:END ===';

/** Replace (or append) the authored region inside `host`. */
export function spliceRegion(host: string, body: string): string {
  const begin = host.indexOf(BEGIN_MARKER);
  const end = host.indexOf(END_MARKER);
  const block = `${BEGIN_MARKER}\n${body}\n${END_MARKER}`;
  if (begin >= 0 && end > begin) {
    return host.slice(0, begin) + block + host.slice(end + END_MARKER.length);
  }
  const sep = host.length === 0 || host.endsWith('\n\n') ? '' : host.endsWith('\n') ? '\n' : '\n\n';
  return host + sep + block + '\n';
}

/** Extract the authored region, or null when absent. */
export function extractRegion(host: string): string | null {
  const begin = host.indexOf(BEGIN_MARKER);
  const end = host.indexOf(END_MARKER);
  if (begin < 0 || end <= begin) return null;
  return host.slice(begin + BEGIN_MARKER.length, end).replace(/^\n/, '').replace(/\n$/, '');
}
