#pragma once

#include <cstring>
#include <memory>

#include "infra/component.h"
#include "infra/event.h"
#include "infra/link.h"
#include "iss_events.h"
#include "microarch/registry.hpp"

// === ISS-AUTHORED:BEGIN — generated by the ISS canvas. Edit via the canvas, not by hand. ===
namespace Unit1 {

class Out1 : public Component {
  public:
    explicit Out1() : Component("Unit1.Out1") {
        configureLink();
    }
    void handler(Event& ev) override {
        (void)ev;
    }
    void setLink(const char* port, Link* link) {
        (void)port;
        (void)link;
    }
    void configureLink() {
    }
    void wire(microarch::Registry& registry) {
        (void)registry;
    }
};

} // namespace Unit1
// === ISS-AUTHORED:END ===
